# Generated by Django 3.2.24 on 2024-07-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0003_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Exco',
        ),
    ]
