# Generated by Django 3.2.24 on 2024-07-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0004_rename_portfolio_exco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exco',
            new_name='Portfolio',
        ),
    ]
