# Generated by Django 3.2.24 on 2024-07-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0005_rename_exco_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='level',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='degree',
            field=models.CharField(default='taiwo', max_length=350),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(default='photo', upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='mobile',
            field=models.CharField(default='foo', max_length=350),
        ),
    ]
