# Generated by Django 3.2.24 on 2024-07-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0006_auto_20240720_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='post',
            new_name='exco',
        ),
    ]
