# Generated by Django 3.2.24 on 2024-07-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0007_rename_post_portfolio_exco'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='event', upload_to='event/')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
