# Generated by Django 3.2.24 on 2024-07-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0008_recentevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpComingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=350)),
                ('title', models.CharField(max_length=350)),
            ],
        ),
    ]
