# Generated by Django 3.2.24 on 2024-07-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0010_auto_20240724_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activestudent',
            name='Building_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='activestudent',
            name='Room_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='activestudent',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
