# Generated by Django 3.2.24 on 2024-07-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0011_auto_20240725_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activestudent',
            name='Building_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activestudent',
            name='Room_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
