# Generated by Django 3.2.24 on 2024-07-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0012_auto_20240726_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activestudent',
            name='Address',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='activestudent',
            name='Building_number',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='activestudent',
            name='Room_number',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
