# Generated by Django 3.2.24 on 2024-07-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0013_auto_20240727_0854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Head',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='RecentEvent',
        ),
        migrations.DeleteModel(
            name='Speech',
        ),
        migrations.DeleteModel(
            name='UpComingEvent',
        ),
    ]
