# Generated by Django 3.2.24 on 2024-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0014_auto_20240727_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=350)),
                ('title', models.CharField(blank=True, max_length=350)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(blank=True, max_length=350)),
                ('first_name', models.CharField(blank=True, max_length=350)),
                ('email', models.CharField(max_length=350, unique=True)),
                ('password', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exco', models.CharField(max_length=350)),
                ('name', models.CharField(max_length=350)),
                ('department', models.CharField(max_length=350)),
                ('degree', models.CharField(default='taiwo', max_length=350)),
                ('mobile', models.CharField(default='foo', max_length=350)),
                ('photo', models.ImageField(default='photo', upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='RecentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='event', upload_to='event/')),
                ('title', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3500)),
                ('name', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='UpComingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=350)),
                ('title', models.CharField(max_length=350)),
            ],
        ),
    ]
