# Generated by Django 3.2.24 on 2024-07-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0015_attendance_head_portfolio_recentevent_speech_upcomingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activestudent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
