# Generated by Django 3.2.24 on 2024-07-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0016_alter_activestudent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
