# Generated by Django 3.2.24 on 2024-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0018_remove_activestudent_emergency_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activestudent',
            name='Nextofkin_city',
        ),
        migrations.AlterField(
            model_name='activestudent',
            name='FamilyinSaudi',
            field=models.CharField(max_length=350),
        ),
    ]
