# Generated by Django 3.2.24 on 2024-07-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0020_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=350)),
                ('First_name', models.CharField(max_length=350)),
                ('Degree', models.CharField(max_length=350)),
                ('College', models.CharField(max_length=350)),
                ('Phone_number', models.CharField(max_length=350)),
                ('Address', models.CharField(blank=True, max_length=350, null=True)),
                ('FamilyinSaudi', models.CharField(max_length=350)),
                ('Building_number', models.CharField(blank=True, max_length=350, null=True)),
                ('Room_number', models.CharField(blank=True, max_length=350, null=True)),
                ('Nextofkin_mobile', models.CharField(max_length=350)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('auth_email', models.CharField(max_length=350, unique=True)),
                ('auth_password', models.CharField(max_length=350)),
                ('verify_token', models.CharField(max_length=16, null=True)),
                ('email_sent_condition_met', models.BooleanField(default=True, null=True)),
                ('Gender', models.CharField(max_length=350)),
            ],
        ),
        migrations.AddField(
            model_name='activestudent',
            name='Gender',
            field=models.CharField(default=True, max_length=350),
        ),
    ]
