# Generated by Django 3.2.24 on 2024-08-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0023_auto_20240804_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activestudent',
            name='Gender',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
