# Generated by Django 3.2.24 on 2024-08-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0024_alter_activestudent_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activestudent',
            name='Gender',
            field=models.CharField(default=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='activestudent',
            name='Nextofkin_mobile',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
