# Generated by Django 3.2.24 on 2024-08-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0025_auto_20240805_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activestudent',
            name='Gender',
            field=models.CharField(max_length=350),
        ),
    ]
