# Generated by Django 3.2.24 on 2024-08-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0026_alter_activestudent_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femalestudent',
            name='Gender',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='femalestudent',
            name='Nextofkin_mobile',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
