# Generated by Django 3.2.24 on 2024-08-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0027_auto_20240806_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='Occupation',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
